# SPDX-FileCopyrightText: 2026 Kevin Marchais
# SPDX-License-Identifier: GPL-3.0-or-later
"""Translate glyph specifications into Geometry-Nodes-instanced bpy objects.

PyVista's ``mesh.glyph(...)`` returns a *baked* PolyData — every glyph
copy is materialised as actual geometry, then merged. For ``N`` points
and a ``V``-vertex glyph mesh that's ``N * V`` vertices to push through
Cycles. The bridge avoids that by hosting one copy of the glyph mesh
and using Blender's :class:`GeometryNodeInstanceOnPoints` to generate
the instances at render time: one ``V``-vertex geom data block + one
``N``-vertex points data block + one node group.

Per-point ``orient`` (3D vector field) is read via a
``GeometryNodeInputNamedAttribute`` and fed through
``FunctionNodeAlignRotationToVector`` to produce the instance rotation.
Per-point ``scale`` (scalar field) is multiplied by the global
``factor`` and fed into the ``Scale`` socket directly. Either or both
can be omitted — defaults to identity rotation / unit scale.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import bpy
import numpy as np

from pyvista_blender._glyph import GlyphSpec

if TYPE_CHECKING:
    import pyvista as pv

__all__ = [
    "GlyphSpec",
    "build_glyph_channel_image",
    "inject_glyph_channel_override",
    "translate_glyph",
]


def translate_glyph(spec: GlyphSpec, ordinal: int) -> bpy.types.Object:
    """Materialise one :class:`GlyphSpec` as an instancing bpy object.

    The returned object carries:

    * A vertex-only bpy mesh holding the source dataset's points, plus
      ``orient`` / ``scale`` attributes copied over if the spec asks for
      them.
    * A ``NODES`` modifier driving a fresh :class:`GeometryNodeTree`
      that instances ``spec.geom`` at every vertex with the requested
      rotation + scale.

    The glyph geom is hidden from camera rays so the original mesh
    doesn't appear at the origin alongside the instances.

    Parameters
    ----------
    spec
        Source dataset + glyph shape + field names.
    ordinal
        Disambiguator for the bpy data block names so multiple
        ``add_glyph(...)`` calls don't collide.

    Returns
    -------
    bpy.types.Object
        The instancing parent object, linked into the active scene.

    """
    name = spec.name or f"PVGlyph_{ordinal}"
    geom_obj = _build_geom_object(spec.geom, name)
    points_obj = _build_points_object(spec, name)
    _attach_instancer_modifier(points_obj, geom_obj, spec, name)
    return points_obj


def _build_geom_object(geom: pv.DataSet, base_name: str) -> bpy.types.Object:
    """Materialise the glyph shape as a hidden bpy mesh+object.

    Returns
    -------
    bpy.types.Object
        Hidden from camera rays (``hide_render = True``) — only the
        instances generated by the GN modifier should appear.

    """
    surface = geom.extract_surface(algorithm="dataset_surface").triangulate()
    verts = np.ascontiguousarray(surface.points, dtype=np.float32)
    tris = np.ascontiguousarray(surface.regular_faces, dtype=np.int32)

    mesh_data = bpy.data.meshes.new(f"{base_name}_geom")
    mesh_data.vertices.add(len(verts))
    mesh_data.vertices.foreach_set("co", verts.ravel())
    mesh_data.loops.add(len(tris) * 3)
    mesh_data.loops.foreach_set("vertex_index", tris.ravel())
    mesh_data.polygons.add(len(tris))
    mesh_data.polygons.foreach_set(
        "loop_start", np.arange(len(tris), dtype=np.int32) * 3
    )
    mesh_data.polygons.foreach_set("loop_total", np.full(len(tris), 3, dtype=np.int32))
    mesh_data.update(calc_edges=True)
    mesh_data.validate()

    obj = bpy.data.objects.new(f"{base_name}_geom", mesh_data)
    obj.hide_render = True
    bpy.context.scene.collection.objects.link(obj)
    return obj


def _build_points_object(spec: GlyphSpec, base_name: str) -> bpy.types.Object:
    """Materialise the source points as a vertex-only bpy mesh.

    Per-point orient (vector) and scale (scalar) fields are written to
    POINT-domain attributes so the GN node group can read them by name.

    Returns
    -------
    bpy.types.Object
        Object wrapping the freshly-allocated vertex-only mesh.

    """
    points = np.ascontiguousarray(spec.source.points, dtype=np.float32)
    mesh_data = bpy.data.meshes.new(f"{base_name}_points")
    mesh_data.vertices.add(len(points))
    mesh_data.vertices.foreach_set("co", points.ravel())
    mesh_data.update()

    if spec.orient and spec.orient in spec.source.point_data:
        vectors = np.ascontiguousarray(
            spec.source.point_data[spec.orient], dtype=np.float32
        )
        attr = mesh_data.attributes.new(
            name="pv_orient", type="FLOAT_VECTOR", domain="POINT"
        )
        attr.data.foreach_set("vector", vectors.ravel())

    if spec.scale and spec.scale in spec.source.point_data:
        scalars = np.ascontiguousarray(
            spec.source.point_data[spec.scale], dtype=np.float32
        )
        attr = mesh_data.attributes.new(name="pv_scale", type="FLOAT", domain="POINT")
        attr.data.foreach_set("value", scalars.ravel())

    obj = bpy.data.objects.new(f"{base_name}_points", mesh_data)
    bpy.context.scene.collection.objects.link(obj)
    return obj


def _attach_instancer_modifier(
    points_obj: bpy.types.Object,
    geom_obj: bpy.types.Object,
    spec: GlyphSpec,
    base_name: str,
) -> None:
    """Build the GN node group + modifier that drives the instancing."""
    tree = bpy.data.node_groups.new(f"{base_name}_GN", "GeometryNodeTree")
    interface = tree.interface
    interface.new_socket("Geometry", in_out="INPUT", socket_type="NodeSocketGeometry")
    interface.new_socket("Geometry", in_out="OUTPUT", socket_type="NodeSocketGeometry")

    group_input = tree.nodes.new("NodeGroupInput")
    group_input.location = (-600, 0)
    group_output = tree.nodes.new("NodeGroupOutput")
    group_output.location = (600, 0)

    object_info = tree.nodes.new("GeometryNodeObjectInfo")
    object_info.location = (-400, -200)
    object_info.inputs["Object"].default_value = geom_obj
    object_info.inputs["As Instance"].default_value = True

    instancer = tree.nodes.new("GeometryNodeInstanceOnPoints")
    instancer.location = (0, 0)
    tree.links.new(group_input.outputs["Geometry"], instancer.inputs["Points"])
    tree.links.new(object_info.outputs["Geometry"], instancer.inputs["Instance"])

    if spec.orient:
        rotation_socket = _build_orient_chain(tree)
        tree.links.new(rotation_socket, instancer.inputs["Rotation"])

    scale_socket = _build_scale_chain(tree, spec)
    tree.links.new(scale_socket, instancer.inputs["Scale"])

    tree.links.new(instancer.outputs["Instances"], group_output.inputs["Geometry"])

    modifier = points_obj.modifiers.new(name="PVGlyph", type="NODES")
    modifier.node_group = tree


def _build_orient_chain(tree: bpy.types.NodeTree) -> bpy.types.NodeSocket:
    """Read ``pv_orient`` and align the instance's +Z axis to that vector.

    Returns
    -------
    bpy.types.NodeSocket
        The terminal ``Rotation`` socket to plug into the instancer.

    """
    named_attr = tree.nodes.new("GeometryNodeInputNamedAttribute")
    named_attr.location = (-400, 100)
    named_attr.data_type = "FLOAT_VECTOR"
    named_attr.inputs["Name"].default_value = "pv_orient"

    align = tree.nodes.new("FunctionNodeAlignRotationToVector")
    align.location = (-200, 100)
    tree.links.new(named_attr.outputs["Attribute"], align.inputs["Vector"])
    return align.outputs["Rotation"]


def _build_scale_chain(
    tree: bpy.types.NodeTree, spec: GlyphSpec
) -> bpy.types.NodeSocket:
    """Compute per-point scale = ``factor * pv_scale``.

    When ``spec.scale`` is ``None`` the chain collapses to a constant
    vector ``(factor, factor, factor)`` so every glyph gets the same
    uniform size.

    Returns
    -------
    bpy.types.NodeSocket
        The terminal Vector output to plug into the instancer's Scale.

    """
    factor = float(spec.factor)
    combine = tree.nodes.new("ShaderNodeCombineXYZ")
    combine.location = (-200, -100)

    if spec.scale:
        named = tree.nodes.new("GeometryNodeInputNamedAttribute")
        named.location = (-600, -100)
        named.data_type = "FLOAT"
        named.inputs["Name"].default_value = "pv_scale"

        multiply = tree.nodes.new("ShaderNodeMath")
        multiply.location = (-400, -100)
        multiply.operation = "MULTIPLY"
        multiply.inputs[1].default_value = factor
        tree.links.new(named.outputs["Attribute"], multiply.inputs[0])

        for axis in ("X", "Y", "Z"):
            tree.links.new(multiply.outputs["Value"], combine.inputs[axis])
    else:
        for axis in ("X", "Y", "Z"):
            combine.inputs[axis].default_value = factor

    return combine.outputs["Vector"]


# --------------------------------------------------------------------- #
# bake_glyphs: per-channel image bakes + GN sub-graph injection
# --------------------------------------------------------------------- #


def build_glyph_channel_image(
    channel_name: str,
    frames: list[tuple[int, np.ndarray]],
    *,
    base_name: str,
) -> bpy.types.Image:
    """Pack per-frame channel data as a float RGBA bpy image.

    Layout: rows = frames (frame 0 at the bottom row, matching bpy's
    bottom-up pixel order), columns = point indices, channels = RGBA.
    Vector channels write into RGB with alpha=1; scalar channels write
    ``(value, 0, 0, 1)`` so the same image format handles both.

    Parameters
    ----------
    channel_name
        ``"positions"`` / ``"orient"`` / ``"scale"``. Anything other
        than ``"scale"`` writes into RGB; ``"scale"`` writes into R only.
    frames
        Per-frame ``(frame_index, values)`` pairs. ``values`` is
        ``(N_points, 3)`` for vector channels, ``(N_points,)`` for
        scalar. All frames must have the same N_points.
    base_name
        Name prefix for the image data-block (typically the bpy
        points object's name).

    Returns
    -------
    bpy.types.Image
        Float-buffer image already loaded into ``bpy.data.images`` and
        packed via :meth:`bpy.types.Image.pack` so it embeds inside
        the .blend on save.

    """
    n_frames = len(frames)
    n_points = frames[0][1].shape[0]
    image_name = f"{base_name}__{channel_name}.exr"

    existing = bpy.data.images.get(image_name)
    if existing is not None:
        bpy.data.images.remove(existing)

    image = bpy.data.images.new(
        image_name, width=n_points, height=n_frames, alpha=True, float_buffer=True
    )

    pixels = np.zeros((n_frames, n_points, 4), dtype=np.float32)
    pixels[..., 3] = 1.0
    for row, (_frame_index, values) in enumerate(frames):
        if channel_name in {"positions", "orient"}:
            pixels[row, :, :3] = values
        else:
            pixels[row, :, 0] = values

    image.pixels.foreach_set(pixels.ravel())
    image.update()
    image.pack()
    return image


def inject_glyph_channel_override(
    tree: bpy.types.NodeTree,
    channel_name: str,
    image: bpy.types.Image,
    *,
    n_frames: int,
    frame_start: int,
) -> None:
    """Splice a per-frame override sub-graph upstream of the glyph instancer.

    The sub-graph samples ``image`` at
    ``((point_index + 0.5) / n_points, (frame - frame_start + 0.5) / n_frames)``
    and either pipes the result into a ``Set Position`` node (positions
    channel) or a ``Store Named Attribute`` node (``pv_orient`` /
    ``pv_scale``). The stored attribute is read by the existing
    ``Input Named Attribute`` nodes downstream, so the instancer
    consumes the per-frame value without further wiring changes.
    """
    instancer = _find_node(tree, "GeometryNodeInstanceOnPoints")
    group_input = _find_node(tree, "NodeGroupInput")
    if instancer is None or group_input is None:
        return

    sampler_socket = _build_glyph_image_sampler(
        tree, image, n_frames=n_frames, frame_start=frame_start
    )
    upstream_socket = _current_geometry_source_into(
        tree, instancer.inputs["Points"], fallback=group_input.outputs["Geometry"]
    )

    if channel_name == "positions":
        set_pos = tree.nodes.new("GeometryNodeSetPosition")
        set_pos.location = (-300, 200)
        tree.links.new(upstream_socket, set_pos.inputs["Geometry"])
        tree.links.new(sampler_socket, set_pos.inputs["Position"])
        _relink(tree, instancer.inputs["Points"], set_pos.outputs["Geometry"])
        return

    store = tree.nodes.new("GeometryNodeStoreNamedAttribute")
    store.location = (-300, 200)
    store.domain = "POINT"
    if channel_name == "orient":
        store.data_type = "FLOAT_VECTOR"
        store.inputs["Name"].default_value = "pv_orient"
        tree.links.new(sampler_socket, store.inputs["Value"])
    else:
        store.data_type = "FLOAT"
        store.inputs["Name"].default_value = "pv_scale"
        sep = tree.nodes.new("ShaderNodeSeparateXYZ")
        sep.location = (-450, 100)
        tree.links.new(sampler_socket, sep.inputs[0])
        tree.links.new(sep.outputs["X"], store.inputs["Value"])
    tree.links.new(upstream_socket, store.inputs["Geometry"])
    _relink(tree, instancer.inputs["Points"], store.outputs["Geometry"])


def _find_node(tree: bpy.types.NodeTree, bl_idname: str) -> bpy.types.Node | None:
    """Return the first node in ``tree`` matching ``bl_idname`` (or ``None``).

    Returns
    -------
    bpy.types.Node or None
        First matching node, or ``None`` when the tree carries none of
        that type (defensive: a tree not built by ``translate_glyph``).

    """
    for node in tree.nodes:
        if node.bl_idname == bl_idname:
            return node
    return None


def _current_geometry_source_into(
    tree: bpy.types.NodeTree,
    target: bpy.types.NodeSocket,
    *,
    fallback: bpy.types.NodeSocket,
) -> bpy.types.NodeSocket:
    """Return the socket currently feeding ``target``, or ``fallback``.

    Returns
    -------
    bpy.types.NodeSocket
        The existing upstream socket on the first link into ``target``,
        or ``fallback`` when no such link exists.

    """
    for link in tree.links:
        if link.to_socket is target:
            return link.from_socket
    return fallback


def _relink(
    tree: bpy.types.NodeTree,
    to_socket: bpy.types.NodeSocket,
    new_from_socket: bpy.types.NodeSocket,
) -> None:
    """Drop any existing link into ``to_socket`` and connect ``new_from_socket``."""
    for link in list(tree.links):
        if link.to_socket is to_socket:
            tree.links.remove(link)
    tree.links.new(new_from_socket, to_socket)


def _build_glyph_image_sampler(
    tree: bpy.types.NodeTree,
    image: bpy.types.Image,
    *,
    n_frames: int,
    frame_start: int,
) -> bpy.types.NodeSocket:
    """Wire a per-frame, per-point GN sampler over ``image``.

    The sampler reads the current vertex index, normalises to atlas U;
    pulls scene time from the Scene Time node, offsets by
    ``frame_start``, normalises to atlas V; combines into a 2D vector;
    feeds an Image Texture node whose ``Image`` input is bound to the
    pre-built ``image``.

    Returns
    -------
    bpy.types.NodeSocket
        The Image Texture's ``Color`` output socket, ready for the
        caller's Set-Position or Store-Named-Attribute sink.

    """
    index = tree.nodes.new("GeometryNodeInputIndex")
    index.location = (-1300, -200)

    n_points = image.size[0]
    u_offset = _gn_math(tree, "ADD", 0.5, index.outputs["Index"])
    u_offset.location = (-1100, -180)
    u_norm = _gn_math(tree, "DIVIDE", float(n_points), u_offset.outputs[0])
    u_norm.location = (-950, -180)

    scene_time = tree.nodes.new("GeometryNodeInputSceneTime")
    scene_time.location = (-1300, -340)
    frame_index = _gn_math(
        tree, "SUBTRACT", float(frame_start), scene_time.outputs["Frame"]
    )
    frame_index.location = (-1100, -340)
    v_offset = _gn_math(tree, "ADD", 0.5, frame_index.outputs[0])
    v_offset.location = (-950, -340)
    v_norm = _gn_math(tree, "DIVIDE", float(n_frames), v_offset.outputs[0])
    v_norm.location = (-800, -340)

    combine = tree.nodes.new("ShaderNodeCombineXYZ")
    combine.location = (-650, -260)
    tree.links.new(u_norm.outputs[0], combine.inputs[0])
    tree.links.new(v_norm.outputs[0], combine.inputs[1])
    combine.inputs[2].default_value = 0.0

    img_node = tree.nodes.new("GeometryNodeImageTexture")
    img_node.location = (-450, -260)
    img_node.interpolation = "Closest"
    img_node.inputs["Image"].default_value = image
    tree.links.new(combine.outputs[0], img_node.inputs["Vector"])
    return img_node.outputs["Color"]


def _gn_math(
    tree: bpy.types.NodeTree,
    operation: str,
    const: float,
    socket: bpy.types.NodeSocket,
) -> bpy.types.Node:
    """Build a Math node computing ``socket {op} const``.

    Returns
    -------
    bpy.types.Node
        The new ``ShaderNodeMath`` with ``socket`` wired into input 0.

    """
    node = tree.nodes.new("ShaderNodeMath")
    node.operation = operation
    node.inputs[1].default_value = const
    tree.links.new(socket, node.inputs[0])
    return node
